spring:
  application:
    name: booking-service
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8200
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: swagger
    use-root-path: true

customer:
  service:
    url: http://localhost:8201
    username: admin
    password: is_a_lie

flight:
  service:
    url: http://localhost:8202
    username: admin
    password: is_a_lie

queue:
  service:
    destination: notification

